feature/src/main/java/com/teamdontbe/feature/notification/NotificationFragment.kt
feature/src/main/res/layout/fragment_notification.xml
feature/src/main/res/layout/fragment_posting.xml
feature/src/main/res/layout/view_appbar.xml
feature/src/main/res/values/strings.xml

- closed #29
- 공통 사용 앱바 구현
- (맡은) 글쓰기랑 알림 뷰에만 include 사용

[Feature/#29] appbar 구현

---

feature/src/main/java/com/teamdontbe/feature/posting/PostingFragment.kt
feature/src/main/res/drawable/shape_error_line_10_ring.xml
feature/src/main/res/drawable/shape_gray_03_line_10_ring.xml
feature/src/main/res/drawable/shape_primary_line_10_ring.xml
feature/src/main/res/layout/fragment_posting.xml

- closed #42 
- 게시글 작성하기 progress bar 구현
- 홈 화면 > 글쓰기 > 게시 > 홈 화면 이동 후 글쓰기 bottom navi 작동 안하는 이슈 존재!!!
- 정말 저수준 코드.. 코리 듬뿍듬뿍 좋아요

[Feature/#42] 게시글 작성하기 progressbar 구현

---

feature/src/main/res/drawable/ic_home_heart_primary_active.xml
feature/src/main/res/drawable/sel_home_heart.xml
feature/src/main/res/layout/item_comment.xml

- closed #61
- 댓글 아이템 ui 구현
- 
마이페이지에서 가져다 쓰면 됨!

[Feature/#61] comment item UI

---

feature/src/main/java/com/teamdontbe/feature/notification/NotificationFragment.kt
feature/src/main/res/drawable/ic_notification_empty.xml
feature/src/main/res/layout/fragment_notification.xml
feature/src/main/res/values/strings.xml

- closed #59
- 노티 empty view 구현
- list empty일 때 visible 처리

[Feature/#59] 노티 empty ui 구현

---

app/src/main/java/com/teamdontbe/dontbe/di/HomeModule.kt
app/src/main/java/com/teamdontbe/dontbe/di/LoginModule.kt
app/src/main/java/com/teamdontbe/dontbe/di/RetrofitModule.kt
data-remote/src/main/java/com/teamdontbe/data_remote/api/HomeApiService.kt
data-remote/src/main/java/com/teamdontbe/data_remote/datasourceimpl/HomeDataSourceImpl.kt
data/src/main/java/com/teamdontbe/data/datasource/HomeDataSource.kt
data/src/main/java/com/teamdontbe/data/dto/BaseResponse.kt
data/src/main/java/com/teamdontbe/data/dto/response/ResponseFeedDto.kt
data/src/main/java/com/teamdontbe/data/dto/response/ResponseLoginDto.kt
data/src/main/java/com/teamdontbe/data/repositoryimpl/HomeRepositoryImpl.kt
domain/src/main/java/com/teamdontbe/domain/repository/HomeRepository.kt
feature/src/main/java/com/teamdontbe/feature/home/HomeFragment.kt
feature/src/main/java/com/teamdontbe/feature/home/HomeViewModel.kt
feature/src/main/java/com/teamdontbe/feature/login/LoginViewModel.kt

- closed #85 
- home feed list api 통신
- access token에 refresh token 넣어둠 이슈 해결
- base response 명세서 바뀐 것 반영
https://github.com/TeamDon-tBe/ANDROID/assets/98076050/c726b461-e8d4-49f6-93e0-5f20467e0bb8
확실히 페이징 넣어야 할듯 데이터 한번에 받아오니까 로딩이 너무 느리다
로딩 뷰 추후 추가 예정

[Feature/#85] feed list api

---

data-remote/src/main/java/com/teamdontbe/data_remote/api/HomeApiService.kt
data-remote/src/main/java/com/teamdontbe/data_remote/datasourceimpl/HomeDataSourceImpl.kt
data/src/main/java/com/teamdontbe/data/datasource/HomeDataSource.kt
data/src/main/java/com/teamdontbe/data/dto/response/ResponseFeedDto.kt
data/src/main/java/com/teamdontbe/data/repositoryimpl/HomeRepositoryImpl.kt
domain/src/main/java/com/teamdontbe/domain/repository/HomeRepository.kt
feature/src/main/java/com/teamdontbe/feature/home/HomeViewModel.kt
feature/src/main/java/com/teamdontbe/feature/homedetail/HomeDetailFragment.kt

- closed #90 
- 게시물 상세 api
- 
https://github.com/TeamDon-tBe/ANDROID/assets/98076050/2022d646-2c40-469f-8093-99acb488316a
contentId 넣어서 연결하심 됩니다.

[Feature/#90] feed detail api

---

app/src/main/java/com/teamdontbe/dontbe/di/NotificationModule.kt
data-remote/src/main/java/com/teamdontbe/data_remote/api/NotificationApiService.kt
data-remote/src/main/java/com/teamdontbe/data_remote/datasourceimpl/NotificationListDataSourceImpl.kt
data/src/main/java/com/teamdontbe/data/datasource/NotificationListDataSource.kt
data/src/main/java/com/teamdontbe/data/dto/response/ResponseNotificationListDto.kt
data/src/main/java/com/teamdontbe/data/repositoryimpl/NotificationListRepositoryImpl.kt
domain/src/main/java/com/teamdontbe/domain/repository/NotificationListRepository.kt
feature/src/main/java/com/teamdontbe/feature/homedetail/HomeDetailFragment.kt
feature/src/main/java/com/teamdontbe/feature/notification/NotificationFragment.kt
feature/src/main/java/com/teamdontbe/feature/notification/NotificationViewModel.kt
feature/src/main/java/com/teamdontbe/feature/notification/adapter/NotificationViewHolder.kt
feature/src/main/res/navigation/nav_main.xml

- closed #87
- 유저에 해당하는 노티 리스트 조회 API 연결(GET)
https://github.com/TeamDon-tBe/ANDROID/assets/85453429/464ff30b-38c8-4973-910a-e44ff85dc4bd
- 푸하하 내가 최고얌

[Feature/#87] 노티 리스트 조회 API 연결

---

data-remote/src/main/java/com/teamdontbe/data_remote/api/HomeApiService.kt
data-remote/src/main/java/com/teamdontbe/data_remote/datasourceimpl/HomeDataSourceImpl.kt
data/src/main/java/com/teamdontbe/data/datasource/HomeDataSource.kt
data/src/main/java/com/teamdontbe/data/dto/response/ResponseCommentDto.kt
data/src/main/java/com/teamdontbe/data/dto/response/ResponseFeedDto.kt
data/src/main/java/com/teamdontbe/data/repositoryimpl/HomeRepositoryImpl.kt
domain/src/main/java/com/teamdontbe/domain/entity/CommentEntity.kt
domain/src/main/java/com/teamdontbe/domain/entity/FeedEntity.kt
domain/src/main/java/com/teamdontbe/domain/repository/HomeRepository.kt
feature/src/main/java/com/teamdontbe/feature/home/Feed.kt
feature/src/main/java/com/teamdontbe/feature/home/HomeFragment.kt
feature/src/main/java/com/teamdontbe/feature/home/HomeViewModel.kt
feature/src/main/java/com/teamdontbe/feature/home/viewholder/HomeViewHolder.kt
feature/src/main/java/com/teamdontbe/feature/homedetail/HomeDetailCommentAdapter.kt
feature/src/main/java/com/teamdontbe/feature/homedetail/HomeDetailFragment.kt
feature/src/main/java/com/teamdontbe/feature/homedetail/viewholder/HomeDetailCommentViewHolder.kt
feature/src/main/res/layout/fragment_home_detail.xml
feature/src/main/res/layout/item_home_comment.xml
feature/src/main/res/layout/item_home_feed.xml

- closed #89 
- 댓글 리스트 api 연결
- feed 시간 가공해주기
https://github.com/TeamDon-tBe/ANDROID/assets/98076050/cb677e20-c275-481b-b621-6df3568e972b
화이띵. 짜파구리 맛있다.

[Feature/#89] : comment list api

---

data-remote/src/main/java/com/teamdontbe/data_remote/api/HomeApiService.kt
data-remote/src/main/java/com/teamdontbe/data_remote/datasourceimpl/HomeDataSourceImpl.kt
data/src/main/java/com/teamdontbe/data/datasource/HomeDataSource.kt
data/src/main/java/com/teamdontbe/data/repositoryimpl/HomeRepositoryImpl.kt
domain/src/main/java/com/teamdontbe/domain/repository/HomeRepository.kt
feature/src/main/java/com/teamdontbe/feature/dialog/DeleteCompleteDialogFragment.kt
feature/src/main/java/com/teamdontbe/feature/dialog/DeleteWithTitleDialogFragment.kt
feature/src/main/java/com/teamdontbe/feature/home/HomeAdapter.kt
feature/src/main/java/com/teamdontbe/feature/home/HomeBottomSheet.kt
feature/src/main/java/com/teamdontbe/feature/home/HomeFragment.kt
feature/src/main/java/com/teamdontbe/feature/home/HomeViewModel.kt
feature/src/main/java/com/teamdontbe/feature/home/viewholder/HomeViewHolder.kt
feature/src/main/java/com/teamdontbe/feature/homedetail/HomeDetailFragment.kt
feature/src/main/java/com/teamdontbe/feature/util/Event.kt
feature/src/main/res/drawable/shape_gray_02_line_10_rec.xml
feature/src/main/res/layout/bottomsheet_complaint_delete.xml
feature/src/main/res/layout/fragment_delete_complete_dialog.xml
feature/src/main/res/layout/fragment_delete_with_title_dialog.xml
feature/src/main/res/values/strings.xml

- closed #99 
- 게시글 삭제 API 연결
- 게시글 삭제 후 갱신
- 게시글 삭제 다이얼로그
- 게시글 신고 다이얼로그
https://github.com/TeamDon-tBe/ANDROID/assets/98076050/e699ed90-e4a2-4891-a7ae-bc43fe244894
화이팅 해야지

{Feature/#99] : delete feed api

---

data-remote/src/main/java/com/teamdontbe/data_remote/api/HomeApiService.kt
data-remote/src/main/java/com/teamdontbe/data_remote/datasourceimpl/HomeDataSourceImpl.kt
data/src/main/java/com/teamdontbe/data/datasource/HomeDataSource.kt
data/src/main/java/com/teamdontbe/data/dto/request/RequestFeedLikedDto.kt
data/src/main/java/com/teamdontbe/data/repositoryimpl/HomeRepositoryImpl.kt
domain/src/main/java/com/teamdontbe/domain/repository/HomeRepository.kt
feature/src/main/java/com/teamdontbe/feature/dialog/DeleteCompleteDialogFragment.kt
feature/src/main/java/com/teamdontbe/feature/dialog/DeleteWithTitleDialogFragment.kt
feature/src/main/java/com/teamdontbe/feature/home/HomeAdapter.kt
feature/src/main/java/com/teamdontbe/feature/home/HomeBottomSheet.kt
feature/src/main/java/com/teamdontbe/feature/home/HomeFragment.kt
feature/src/main/java/com/teamdontbe/feature/home/HomeViewModel.kt
feature/src/main/java/com/teamdontbe/feature/home/viewholder/HomeViewHolder.kt
feature/src/main/java/com/teamdontbe/feature/homedetail/HomeDetailFragment.kt
feature/src/main/java/com/teamdontbe/feature/util/Event.kt
feature/src/main/res/drawable/sel_home_heart.xml
feature/src/main/res/drawable/shape_gray_02_line_10_rec.xml
feature/src/main/res/layout/bottomsheet_complaint_delete.xml
feature/src/main/res/layout/fragment_delete_complete_dialog.xml
feature/src/main/res/layout/fragment_delete_with_title_dialog.xml
feature/src/main/res/layout/item_home_feed.xml
feature/src/main/res/values/strings.xml

- closed #105
- 피드 좋아요 post api
- 피드 좋아요 delete api
https://github.com/TeamDon-tBe/ANDROID/assets/98076050/3d0847f8-f8a2-46b2-9fd0-17f68bb3ed19

[Feature/#105] : like api

---

data-remote/src/main/java/com/teamdontbe/data_remote/api/HomeApiService.kt

- closed #115 
- trigger type 변경
-

#115 [HOTFIX] : trigger type 변경

---

data-remote/src/main/java/com/teamdontbe/data_remote/api/NotificationApiService.kt
data-remote/src/main/java/com/teamdontbe/data_remote/datasourceimpl/NotificationDataSourceImpl.kt
data/src/main/java/com/teamdontbe/data/datasource/NotificationDataSource.kt
data/src/main/java/com/teamdontbe/data/repositoryimpl/NotificationRepositoryImpl.kt
domain/src/main/java/com/teamdontbe/domain/repository/NotificationRepository.kt
feature/src/main/java/com/teamdontbe/feature/MainActivity.kt
feature/src/main/java/com/teamdontbe/feature/notification/NotificationFragment.kt
feature/src/main/java/com/teamdontbe/feature/notification/NotificationViewModel.kt
feature/src/main/java/com/teamdontbe/feature/notification/adapter/NotificationViewHolder.kt
feature/src/main/res/layout/item_notification_feed.xml

- closed #97
- 노티 체크 API 연결(PATCH)
- 노티 view model 로직 수정
- 노티 profile img API databinding 연결
- 내가 읽어놓고 왜 count가 0이지..? 고민했던 감자
- 마지막 API 연결 잘 먹고 갑니다~

[Feature/#97] 노티 체크 API 연결

---

app/src/main/java/com/teamdontbe/dontbe/di/PostingModule.kt
data-remote/src/main/java/com/teamdontbe/data_remote/api/PostingApiService.kt
data-remote/src/main/java/com/teamdontbe/data_remote/datasourceimpl/PostingDataSourceImpl.kt
data/src/main/java/com/teamdontbe/data/datasource/PostingDataSource.kt
data/src/main/java/com/teamdontbe/data/dto/request/RequestPostingDto.kt
data/src/main/java/com/teamdontbe/data/repositoryimpl/PostingRepositoryImpl.kt
domain/src/main/java/com/teamdontbe/domain/repository/PostingRepository.kt
feature/src/main/java/com/teamdontbe/feature/login/LoginActivity.kt
feature/src/main/java/com/teamdontbe/feature/onboarding/OnboardingAdapter.kt
feature/src/main/java/com/teamdontbe/feature/onboarding/OnboardingFourthFragment.kt
feature/src/main/java/com/teamdontbe/feature/onboarding/OnboardingFragment.kt
feature/src/main/java/com/teamdontbe/feature/posting/PostingFragment.kt
feature/src/main/java/com/teamdontbe/feature/posting/PostingViewModel.kt
feature/src/main/res/layout/fragment_onboarding.xml
feature/src/main/res/layout/fragment_posting.xml
feature/src/main/res/layout/item_onboarding_fourth.xml
feature/src/main/res/values/strings.xml

- closed #86 
- 게시물 작성하기 API 연결(POST)
- 게시물 작성하기 API 연결(POST)
먼지야 온보딩 posting, 구현 해둠! pr 글 써줘 -> 적용 완

[Feature/#86] : 게시물 및 온보딩 한 줄 소개 작성하기 API 연결

---

data-remote/src/main/java/com/teamdontbe/data_remote/api/LoginApiService.kt
data-remote/src/main/java/com/teamdontbe/data_remote/datasourceimpl/LoginDataSourceImpl.kt
data/src/main/java/com/teamdontbe/data/datasource/LoginDataSource.kt
data/src/main/java/com/teamdontbe/data/dto/request/RequestProfileEditDto.kt
data/src/main/java/com/teamdontbe/data/repositoryimpl/LoginRepositoryImpl.kt
domain/src/main/java/com/teamdontbe/domain/repository/LoginRepository.kt
feature/src/main/java/com/teamdontbe/feature/SplashActivity.kt
feature/src/main/java/com/teamdontbe/feature/mypage/MyPageFragment.kt
feature/src/main/java/com/teamdontbe/feature/signup/SignUpAgreeActivity.kt
feature/src/main/java/com/teamdontbe/feature/signup/SignUpProfileActivity.kt
feature/src/main/java/com/teamdontbe/feature/signup/SignUpProfileViewModel.kt
feature/src/main/res/layout/activity_sign_up_profile.xml

- closed #113 
- 유저 닉네임 한줄소개 수정 api연결
- 2가지 화면에서 오는 흐름 분기 처리 후 2가지 화면으로 가는 흐름 분기 처리

[Feature/#113] 유저 닉네임 한줄소개 수정 api 연결

---

feature/build.gradle.kts
feature/src/main/java/com/teamdontbe/feature/home/HomeFragment.kt
feature/src/main/java/com/teamdontbe/feature/notification/NotificationFragment.kt
feature/src/main/java/com/teamdontbe/feature/notification/adapter/NotificationViewHolder.kt
feature/src/main/res/layout/fragment_home.xml
feature/src/main/res/layout/fragment_notification.xml
feature/src/main/res/layout/item_notification_feed.xml
gradle/libs.versions.toml

- closed #119
- 스와이프 로딩뷰 구현
- 안드는 왜 스와이프가 안이쁠까요?

[Feature/#119] 로딩뷰 구현

---

core-ui/src/main/java/com/teamdontbe/core_ui/util/intent/Intent.kt
feature/src/main/java/com/teamdontbe/feature/MainActivity.kt
feature/src/main/java/com/teamdontbe/feature/signup/SignUpProfileActivity.kt
feature/src/main/java/com/teamdontbe/feature/signup/SignUpProfileViewModel.kt
feature/src/main/java/com/teamdontbe/feature/signup/UserProfileModel.kt

- closed #123 
- 유저 정보 데이터 메인액티비티 전달
- 
메인에서 받아서 쓰시면 됩니두!

[Feature/#123] 유저 정보 데이터 메인액티비티 전달

---

feature/src/main/java/com/teamdontbe/feature/onboarding/OnboardingFourthFragment.kt
feature/src/main/java/com/teamdontbe/feature/onboarding/OnboardingFragment.kt
feature/src/main/java/com/teamdontbe/feature/onboarding/OnboardingViewModel.kt
feature/src/main/java/com/teamdontbe/feature/posting/PostingViewModel.kt
feature/src/main/res/layout/fragment_onboarding.xml
feature/src/main/res/layout/item_onboarding_fourth.xml

- closed #124
- 온보딩 한 줄 소개 -> 마이페이지 한 줄 소개로 연결(PATCH)
- 찬우오빠 도와줘~

[Feature/#124] 온보딩 - 마이페이지 API 연결

---

feature/src/main/java/com/teamdontbe/feature/home/HomeAdapter.kt
feature/src/main/java/com/teamdontbe/feature/home/HomeFragment.kt
feature/src/main/java/com/teamdontbe/feature/home/viewholder/HomeViewHolder.kt
feature/src/main/java/com/teamdontbe/feature/mypage/MyPageFragment.kt
feature/src/main/java/com/teamdontbe/feature/mypage/bottomsheet/MyPageAnotherUserBottomSheet.kt
feature/src/main/java/com/teamdontbe/feature/mypage/comment/MyPageCommentAdapter.kt
feature/src/main/java/com/teamdontbe/feature/mypage/comment/MyPageCommentFragment.kt
feature/src/main/java/com/teamdontbe/feature/mypage/comment/MyPageCommentViewHolder.kt
feature/src/main/java/com/teamdontbe/feature/mypage/feed/MyPageFeedFragment.kt
feature/src/main/res/navigation/nav_main.xml

- closed #127 
- 마이페이지 분기 처리
- 
<image src="https://github.com/TeamDon-tBe/ANDROID/assets/106955456/441eb827-dc91-479f-b485-4399bb23f8fb" width=32%><image src="https://github.com/TeamDon-tBe/ANDROID/assets/106955456/00a9c055-8ca1-4958-8420-d65388cdd783" width=32%>

[Feature/#127] my page branch processing

---

feature/src/main/java/com/teamdontbe/feature/home/HomeFragment.kt
feature/src/main/java/com/teamdontbe/feature/mypage/MyPageFragment.kt
feature/src/main/java/com/teamdontbe/feature/mypage/MyPageModel.kt
feature/src/main/java/com/teamdontbe/feature/mypage/MyPageVpAdapter.kt
feature/src/main/java/com/teamdontbe/feature/mypage/comment/MyPageCommentFragment.kt
feature/src/main/java/com/teamdontbe/feature/mypage/feed/MyPageFeedFragment.kt
feature/src/main/java/com/teamdontbe/feature/signup/SignUpProfileActivity.kt

- closed #130 
- 병합 시 오류난 부분 수정
-

[Feature/#130] my page fix

---

feature/src/main/java/com/teamdontbe/feature/home/HomeFragment.kt
feature/src/main/java/com/teamdontbe/feature/mypage/MyPageFragment.kt
feature/src/main/java/com/teamdontbe/feature/mypage/MyPageModel.kt
feature/src/main/java/com/teamdontbe/feature/mypage/MyPageVpAdapter.kt
feature/src/main/java/com/teamdontbe/feature/mypage/comment/MyPageCommentAdapter.kt
feature/src/main/java/com/teamdontbe/feature/mypage/comment/MyPageCommentFragment.kt
feature/src/main/java/com/teamdontbe/feature/mypage/feed/MyPageFeedAdapter.kt
feature/src/main/java/com/teamdontbe/feature/mypage/feed/MyPageFeedFragment.kt
feature/src/main/java/com/teamdontbe/feature/mypage/feed/MyPageFeedViewHolder.kt
feature/src/main/java/com/teamdontbe/feature/mypage/feed/MyPageFeedViewModel.kt
feature/src/main/java/com/teamdontbe/feature/signup/SignUpProfileActivity.kt

- closed #135 
-  마이페이지 피드 좋아요 버튼 서버 통신
- 
https://github.com/TeamDon-tBe/ANDROID/assets/106955456/14bddf07-f6c1-4008-a87e-9e9558fae642

[Feature/#135] my page btn api

---

feature/src/main/java/com/teamdontbe/feature/mypage/MyPageFragment.kt
feature/src/main/java/com/teamdontbe/feature/mypage/bottomsheet/MyPageAnotherUserBottomSheet.kt
feature/src/main/java/com/teamdontbe/feature/mypage/bottomsheet/MyPageDeclarDialogFragment.kt
feature/src/main/java/com/teamdontbe/feature/mypage/bottomsheet/MyPageDeleteDialogFragment.kt
feature/src/main/java/com/teamdontbe/feature/mypage/feed/MyPageFeedAdapter.kt
feature/src/main/java/com/teamdontbe/feature/mypage/feed/MyPageFeedFragment.kt
feature/src/main/java/com/teamdontbe/feature/mypage/feed/MyPageFeedViewHolder.kt
feature/src/main/java/com/teamdontbe/feature/mypage/feed/MyPageFeedViewModel.kt
feature/src/main/res/layout/view_my_page_no_feed.xml
feature/src/main/res/navigation/nav_main.xml

- closed #137 
- my page 신고하기, 삭제 기능
-

[Feature/#137] my page 신고하기, 삭제 기능

---

feature/src/main/java/com/teamdontbe/feature/home/HomeFragment.kt
feature/src/main/java/com/teamdontbe/feature/mypage/MyPageFragment.kt
feature/src/main/java/com/teamdontbe/feature/posting/PostingFragment.kt
feature/src/main/res/layout/fragment_home.xml
feature/src/main/res/layout/fragment_my_page.xml

- closed #141 
- 탭 누를시에 최상단으로 스크롤
-

[Feature/#141] scroll to top

---

feature/src/main/java/com/teamdontbe/feature/home/HomeAdapter.kt
feature/src/main/java/com/teamdontbe/feature/home/HomeFragment.kt
feature/src/main/java/com/teamdontbe/feature/home/viewholder/HomeViewHolder.kt
feature/src/main/java/com/teamdontbe/feature/homedetail/HomeDetailCommentAdapter.kt
feature/src/main/java/com/teamdontbe/feature/homedetail/HomeDetailFragment.kt
feature/src/main/java/com/teamdontbe/feature/homedetail/viewholder/HomeDetailCommentViewHolder.kt
feature/src/main/java/com/teamdontbe/feature/onboarding/OnboardingFourthFragment.kt
feature/src/main/java/com/teamdontbe/feature/util/BindingAdapter.kt
feature/src/main/res/layout/bottomsheet_comment.xml
feature/src/main/res/layout/fragment_home_detail.xml
feature/src/main/res/layout/item_home_comment.xml
feature/src/main/res/layout/item_home_feed.xml

[Feature/#146] : 기본 이미지 넣기

---

feature/src/main/java/com/teamdontbe/feature/mypage/bottomsheet/MyPageTransparentDialogFragment.kt
feature/src/main/java/com/teamdontbe/feature/mypage/comment/MyPageCommentFragment.kt
feature/src/main/java/com/teamdontbe/feature/mypage/feed/MyPageFeedFragment.kt

- closed #
- 투명도 적용 안되는 오류 해결
-

#158 [fix] : 투명도 적용 안되는 오류 해결

---

feature/src/main/java/com/teamdontbe/feature/homedetail/HomeDetailFragment.kt

- closed #163
- home detail comment progress bar animation 적용

#163 [MOD] : home detail comment progress bar animation 적용

---

feature/src/main/java/com/teamdontbe/feature/onboarding/OnboardingFragment.kt
feature/src/main/java/com/teamdontbe/feature/onboarding/OnboardingViewModel.kt

#158 [fix] : 온보딩 화면 url널체크

---

feature/src/main/java/com/teamdontbe/feature/home/HomeFragment.kt
feature/src/main/java/com/teamdontbe/feature/home/HomeViewModel.kt
feature/src/main/java/com/teamdontbe/feature/homedetail/HomeDetailFragment.kt
feature/src/main/java/com/teamdontbe/feature/login/LoginActivity.kt
feature/src/main/res/navigation/nav_main.xml

[FIX] : 좋아요 DELETE 수정

---

feature/src/main/java/com/teamdontbe/feature/homedetail/HomeDetailFragment.kt

#158 [fix] : 홈디테일 안눌리는 오류 수정

---

feature/src/main/java/com/teamdontbe/feature/mypage/MyPageFragment.kt
feature/src/main/java/com/teamdontbe/feature/mypage/comment/MyPageCommentFragment.kt
feature/src/main/java/com/teamdontbe/feature/mypage/feed/MyPageFeedFragment.kt
feature/src/main/java/com/teamdontbe/feature/signup/SignUpAgreeActivity.kt
feature/src/main/java/com/teamdontbe/feature/signup/SignUpProfileActivity.kt
feature/src/main/java/com/teamdontbe/feature/util/KeyStorage.kt
feature/src/main/res/layout/activity_sign_up_agree.xml
feature/src/main/res/layout/view_appbar_with_back.xml

- closed #179 
- 회원가입 화면 전체 선택 버튼 수정
- KeyStorage추가
https://github.com/TeamDon-tBe/ANDROID/assets/106955456/a608294a-6bc0-4b2a-939a-dd365053c22a
keyStorage의 경우 공용으로 쓰는 key값만 우선 저장해 놓았습니다.

[Feature/#179] 회원 가입화면 전체선택 수정

---

app/src/main/java/com/teamdontbe/dontbe/DontBeApp.kt
core-ui/src/main/java/com/teamdontbe/core_ui/view/DuplicateBlockClickListener.kt
data-remote/src/main/java/com/teamdontbe/data_remote/datasourceimpl/HomeDataSourceImpl.kt
data/src/main/java/com/teamdontbe/data/datasource/HomeDataSource.kt
data/src/main/java/com/teamdontbe/data/repositoryimpl/HomeRepositoryImpl.kt
domain/src/main/java/com/teamdontbe/domain/repository/HomeRepository.kt
feature/src/main/java/com/teamdontbe/feature/dialog/DeleteWithTitleDialogFragment.kt
feature/src/main/java/com/teamdontbe/feature/dialog/TransparentDialogFragment.kt
feature/src/main/java/com/teamdontbe/feature/home/Feed.kt
feature/src/main/java/com/teamdontbe/feature/home/HomeAdapter.kt
feature/src/main/java/com/teamdontbe/feature/home/HomeBottomSheet.kt
feature/src/main/java/com/teamdontbe/feature/home/HomeFeedAdapter.kt
feature/src/main/java/com/teamdontbe/feature/home/HomeFragment.kt
feature/src/main/java/com/teamdontbe/feature/home/HomeViewModel.kt
feature/src/main/java/com/teamdontbe/feature/home/viewholder/HomeFeedViewHolder.kt
feature/src/main/java/com/teamdontbe/feature/home/viewholder/HomeViewHolder.kt
feature/src/main/java/com/teamdontbe/feature/homedetail/HomeDetailCommentAdapter.kt
feature/src/main/java/com/teamdontbe/feature/homedetail/HomeDetailFragment.kt
feature/src/main/java/com/teamdontbe/feature/homedetail/viewholder/HomeDetailCommentViewHolder.kt
feature/src/main/java/com/teamdontbe/feature/mypage/MyPageViewModel.kt
feature/src/main/java/com/teamdontbe/feature/mypage/bottomsheet/MyPageTransparentDialogFragment.kt
feature/src/main/java/com/teamdontbe/feature/mypage/comment/MyPageCommentFragment.kt
feature/src/main/java/com/teamdontbe/feature/mypage/feed/MyPageFeedFragment.kt
feature/src/main/java/com/teamdontbe/feature/util/BindingAdapter.kt
feature/src/main/res/layout/bottomsheet_comment.xml
feature/src/main/res/layout/fragment_home_detail.xml
feature/src/main/res/layout/item_home_comment.xml
feature/src/main/res/layout/item_home_feed.xml
feature/src/main/res/layout/item_onboarding_fourth.xml
feature/src/main/res/values/strings.xml

- closed #174 
- home, home detail 리팩토링 (함수화, 코드 정리)
- 투명도, 시간 text 데바 적용 -> BindingAdapter 확인 해보셈
- 먼지가 QA 해준 온보딩 text 제약 수정
- 서버가 요청한 투명도 댓글 분기 처리
투명도 댓글 분기 처리하면서 my page도 조금 건드린 부분 있는데, 궁금하면 9bff92b7740ff9de598eeadf6e498f38d4b3379e
요 커밋 확인 해봐요-! 컨플릭은 제가 해결하겠슴

[Feature/#174] : home refactoring

---

feature/src/main/java/com/teamdontbe/feature/notification/NotificationViewModel.kt
feature/src/main/java/com/teamdontbe/feature/posting/PostingFragment.kt
feature/src/main/res/layout/fragment_posting.xml

- closed #186
- 노티 API null -> failure 처리
- posting 배경색 변경
- posting progress bar include 적용

[Feature/#186] qa fix

---

feature/src/main/java/com/teamdontbe/feature/home/HomeFragment.kt
feature/src/main/java/com/teamdontbe/feature/homedetail/HomeDetailFragment.kt
feature/src/main/java/com/teamdontbe/feature/mypage/authwithdraw/MyPageAuthWithdrawGuideActivity.kt
feature/src/main/java/com/teamdontbe/feature/mypage/authwithdraw/MyPageAuthWithdrawReasonActivity.kt
feature/src/main/java/com/teamdontbe/feature/mypage/comment/MyPageCommentFragment.kt
feature/src/main/java/com/teamdontbe/feature/mypage/feed/MyPageFeedFragment.kt
feature/src/main/java/com/teamdontbe/feature/notification/NotificationFragment.kt
feature/src/main/java/com/teamdontbe/feature/posting/PostingFragment.kt
feature/src/main/java/com/teamdontbe/feature/util/KeyStorage.kt

- closed #188
- 이전에 열었던 188 브랜치 push 안한거 적용
- key storage 파일로 상수 export

#188 [MOD] : key storage 파일로 상수 export

---

app/src/main/java/com/teamdontbe/dontbe/di/WithdrawModule.kt
data-remote/src/main/java/com/teamdontbe/data_remote/api/WithdrawApiService.kt
data-remote/src/main/java/com/teamdontbe/data_remote/datasourceimpl/WithdrawDataSourceImpl.kt
data/src/main/java/com/teamdontbe/data/datasource/WithdrawDataSource.kt
data/src/main/java/com/teamdontbe/data/dto/request/RequestWithdrawDto.kt
data/src/main/java/com/teamdontbe/data/repositoryimpl/WithdrawRepositoryImpl.kt
domain/src/main/java/com/teamdontbe/domain/repository/WithdrawRepository.kt
feature/src/main/java/com/teamdontbe/feature/dialog/DeleteWithTitleWideDialogFragment.kt
feature/src/main/java/com/teamdontbe/feature/mypage/MyPageViewModel.kt
feature/src/main/java/com/teamdontbe/feature/mypage/authwithdraw/MyPageAuthWithdrawGuideActivity.kt
feature/src/main/java/com/teamdontbe/feature/mypage/authwithdraw/MyPageAuthWithdrawReasonActivity.kt
feature/src/main/java/com/teamdontbe/feature/mypage/authwithdraw/MyPageAuthWithdrawViewModel.kt
feature/src/main/java/com/teamdontbe/feature/mypage/bottomsheet/MyPageBottomSheet.kt
feature/src/main/java/com/teamdontbe/feature/util/KeyStorage.kt

- closed #200
- 계정 삭제 기능 구현
- 계정 삭제 API 연결(DELETE)
앱 키 띄어쓰기 저는 매우 화가나요.

[Feature/#200] 계정 삭제 API 연결

---

feature/src/main/java/com/teamdontbe/feature/posting/PostingFragment.kt
feature/src/main/res/values/themes.xml

- closed #220
- posting fragment keyboard 기본으로 안올라오는 이슈 해결
- editText keyboard 프리징 이슈 해결

[Feature/#220] posting qa fix

---

feature/src/main/java/com/teamdontbe/feature/MainActivity.kt
feature/src/main/java/com/teamdontbe/feature/mypage/comment/MyPageCommentFragment.kt
feature/src/main/java/com/teamdontbe/feature/mypage/feed/MyPageFeedFragment.kt

#208 [hotfix] : 마이페이지에서 바텀네비 icon 바뀌는 오류 롤백

---

feature/src/main/java/com/teamdontbe/feature/LoadingActivity.kt
feature/src/main/res/drawable/shape_primary_fill_circle.xml
feature/src/main/res/layout/fragment_notification.xml
feature/src/main/res/layout/item_notification_feed.xml
feature/src/main/res/values/themes.xml

- closed #223
- editText handle 변경
- noti xml 코드 rollback
- loading view 초 변경
- noti item profile img center crop 적용
아~ 대충살자~

[Feature/#223] qa fix

---

feature/src/main/res/values/strings.xml

- closed #236
- posting view 기본 텍스트 변경
정말 뻘쭘한 pr이네요

[Fix/#236] qa fix 

---

data/src/main/java/com/teamdontbe/data/repositoryimpl/LoginRepositoryImpl.kt
domain/src/main/java/com/teamdontbe/domain/repository/LoginRepository.kt
feature/src/main/java/com/teamdontbe/feature/login/LoginActivity.kt
feature/src/main/java/com/teamdontbe/feature/login/LoginViewModel.kt
feature/src/main/res/values/strings.xml
feature/src/main/res/values/textappearances.xml

- closed #223 
- 계정 삭제 후 재가입 예외처리
- 답글 달기로 텍스트 변경
- 텍스트 sp -> dp
마이페이지 갔다가 홈 바텀 아이콘 안눌림 이슈, 마이페이지 답글갔다가 마이페이지 피드 올 시 scroll top 적용 안되는 이슈는
setOnItemReselectedListener가 여러 군데에서 정의되고 있어서 최근 리스너가 덮어져서 생기는 이슈입니다! 
해결해보고 있는 중인데 해결 되면 커밋할게욤 일단 나머지 사항 pr올려둡니다

[Feature/#233] : 최종 Qa

---

feature/src/main/java/com/teamdontbe/feature/mypage/bottomsheet/MyPageTransparentDialogFragment.kt
feature/src/main/java/com/teamdontbe/feature/mypage/comment/MyPageCommentFragment.kt
feature/src/main/java/com/teamdontbe/feature/mypage/feed/MyPageFeedFragment.kt
feature/src/main/res/values/textappearances.xml

- closed #240 
- 전체 텍스트 사이즈 2씩 증가
- 마이페이지 투명도 적용 안되는 오류 수정

[Hotfix/#240] 마이페이지 투명도 오류 수정 + 전체 텍스트 사이즈 수정

---

app/build.gradle.kts
app/src/main/AndroidManifest.xml
app/src/main/java/com/teamdontbe/dontbe/DontBeApp.kt
build-logic/src/main/java/com/teamdontbe/dontbe/plugin/CommonConfigs.kt
core-ui/build.gradle.kts
core-ui/src/main/java/com/teamdontbe/core_ui/util/AmplitudeUtil.kt
feature/build.gradle.kts
feature/proguard-rules.pro
feature/src/main/AndroidManifest.xml
feature/src/main/java/com/teamdontbe/feature/dialog/DeleteWithTitleWideDialogFragment.kt
feature/src/main/java/com/teamdontbe/feature/home/HomeFragment.kt
feature/src/main/java/com/teamdontbe/feature/homedetail/CommentBottomSheet.kt
feature/src/main/java/com/teamdontbe/feature/homedetail/HomeDetailFragment.kt
feature/src/main/java/com/teamdontbe/feature/mypage/comment/MyPageCommentFragment.kt
feature/src/main/java/com/teamdontbe/feature/mypage/feed/MyPageFeedFragment.kt
feature/src/main/java/com/teamdontbe/feature/onboarding/OnboardingFragment.kt
feature/src/main/java/com/teamdontbe/feature/posting/PostingFragment.kt
feature/src/main/java/com/teamdontbe/feature/signup/SignUpProfileActivity.kt
feature/src/main/java/com/teamdontbe/feature/util/KeyStorage.kt
gradle/libs.versions.toml

- closed #245
- amplitude sdk 설정했슴다
- 이벤트마다 track 함수 적용했습니다
api key 슬랙에 남겨둘게요!

[Feature/#245] : amplitude sdk

---

feature/src/main/res/drawable/ic_text_cursor.xml
feature/src/main/res/values/strings.xml
feature/src/main/res/values/themes.xml

- closed #256 
- text cursor UI 변경
- posting 기본 text 변경
헤헷.. 자잘구리... 다들 너무 오랜만

[Feature/#256] posting UI fix

---

feature/src/main/java/com/teamdontbe/feature/homedetail/CommentBottomSheet.kt
feature/src/main/java/com/teamdontbe/feature/posting/PostingFragment.kt
feature/src/main/java/com/teamdontbe/feature/util/Transparent.kt
feature/src/main/res/drawable/ic_home_ghost_fill_green.xml
feature/src/main/res/drawable/shape_error_line_circle.xml
feature/src/main/res/layout/bottomsheet_comment.xml
feature/src/main/res/layout/fragment_posting.xml
feature/src/main/res/layout/fragment_transparent_dialog.xml
feature/src/main/res/layout/item_home_comment.xml
feature/src/main/res/layout/item_home_feed.xml
feature/src/main/res/layout/view_upload_bar.xml
feature/src/main/res/values/strings.xml

- closed #255 
- 투명도 매커니즘 수정
- 투명도 영역 터치 인터렉션 추가
- 투명도 버튼 UI
- 빈 링크칸 삽입되었을 때 게시막기
- 게시글, 답글 올리기 프로그래스바 -> 텍스트로 변경
[sd.webm](https://github.com/TeamDon-tBe/ANDROID/assets/98076050/19b5ef91-4b53-44a5-b473-1d7253c52259)

[Feature/#255] : 3차 스프린트 투명도 & 게시 프로그래스 바 변경

---

data-remote/src/main/java/com/teamdontbe/data_remote/api/HomeApiService.kt
data-remote/src/main/java/com/teamdontbe/data_remote/api/MyPageApiService.kt
data/src/main/java/com/teamdontbe/data/dto/response/ResponseCommentDto.kt
data/src/main/java/com/teamdontbe/data/dto/response/ResponseFeedDto.kt
data/src/main/java/com/teamdontbe/data/dto/response/ResponseMyPageCommentDto.kt
domain/src/main/java/com/teamdontbe/domain/entity/CommentEntity.kt
domain/src/main/java/com/teamdontbe/domain/entity/FeedEntity.kt
feature/src/main/java/com/teamdontbe/feature/home/Feed.kt
feature/src/main/java/com/teamdontbe/feature/util/BindingAdapter.kt
feature/src/main/res/layout/item_home_comment.xml
feature/src/main/res/layout/item_home_feed.xml
feature/src/main/res/layout/item_my_page_comment.xml
feature/src/main/res/values/themes.xml

- closed #259 
- 홈화면 피드 이미지 get
- 홈디테일 화면 comment 리스트 이미지 get
- 마이페이지 피드, comment 이미지 get
- 요기가 어디인지 모르겠네용
홈화면 최상단 홈 getFeedDetail 부분에서 ui가 어떻게 그려지는 지 모르겠어서 일단 이 부분 제외하고 pr올립니다!

[Feature/#259] 이미지 조회

---

feature/src/main/java/com/teamdontbe/feature/homedetail/CommentBottomSheet.kt
feature/src/main/java/com/teamdontbe/feature/posting/PostingFragment.kt
feature/src/main/res/drawable/shape_blue_10_cursor.xml
feature/src/main/res/layout/bottomsheet_comment.xml
feature/src/main/res/layout/fragment_posting.xml

- closed #262 
- link 칸 클릭 시 글자 수 1개 추가되는 오류 수정 (499자일 때 관련해서 서버와 논의 완료)
- 기본 텍스트만 업로드했을 때 null 붙는 오류 수정
- edittext style 통일
[null 텍스트 오류 수정.webm](https://github.com/TeamDon-tBe/ANDROID/assets/98076050/37d43fa8-ebbe-4317-9d38-e4c3483f079e)
null 붙는 오류 제보 땡큐베리머치

[Feature/#262] : 3차 스프린트 link 관련 QA

---

data/src/main/java/com/teamdontbe/data/dto/request/RequestProfileEditDto.kt
data/src/main/java/com/teamdontbe/data/dto/response/ResponseLoginDto.kt
domain/src/main/java/com/teamdontbe/domain/entity/LoginEntity.kt

- closed #265 
- ispushalarmaloowed 추가
-

[#265/FIX] : ispushalarmaloowed 추가
